name: Matlab Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo curl --proto '=https' --tlsv1.2 -sSf https://ssd.mathworks.com/supportfiles/ci/matlab-deps/v0/install.sh | bash
      - name: Install matlab
        run: |
          sudo curl --proto '=https' --tlsv1.2 -sSf https://ssd.mathworks.com/supportfiles/ci/ephemeral-matlab/v0/ci-install.sh | bash
      - name: Test matlab
        run: |
          which matlab
          matlab -batch version
