name: Matlab Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl --output install.sh --proto '=https' --tlsv1.2 -sSf https://ssd.mathworks.com/supportfiles/ci/matlab-deps/v0/install.sh
          chmod +x install.sh
          sudo ./install.sh
      - name: Install matlab
        run: |
          curl --output ci-install.sh --proto '=https' --tlsv1.2 -sSf https://ssd.mathworks.com/supportfiles/ci/ephemeral-matlab/v0/ci-install.sh
          chmod +x ci-install.sh
          sudo ./ci-install.sh
      - name: Test matlab
        run: |
          which matlab
          matlab -batch version
